### ISSUE TITLE
Dates shown are now one day earlier than actual

### ISSUE THREAD

**Issue by smylesg** [Noleli/isyontefearlythisyear#2]
I don't know exactly when it started, but the dates shown are now one day earlier than the actual date.  For example, Tu BiShvat this year is January 28, but the page shows January 27
![image](https://user-images.githubusercontent.com/73486732/103593612-50bc3400-4ec4-11eb-9705-5bf1c0c691c7.png)

This also applies to the graphs.  For example, Rosh Hashana in 1967 was very late due to its being year 8 of the cycle as well as the year before a civil leap year.  It occurred on October 5, but hovering over the 10/04 bar of the graph shows it last occurred on October 4, 1967.
![image](https://user-images.githubusercontent.com/73486732/103593838-e8218700-4ec4-11eb-8fe5-9eaa54014a56.png)

I realize one day will not often change whether a chag is considered early or late, but I thought it might warrant a look.

**Comment by Noleli** [comment]
Thanks for reaching out. As it says at the bottom, “All dates are *erev*, meaning the holiday starts that evening.”

I made that choice because most people are likely to be interested in Chanukah and Pesach, and they think of that in terms of *erev*. That does feel weird for Tu BiShvat, but I felt it was best to be consistent.

If there’s an issue beyond that, feel free to reopen this ticket. Thanks!
